### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Cmdv** [hdgarrood/purescript-numeric-hierarchy-guide#5]
## Logic:

Very clear and made good sense though maybe some Purescript examples to make the connection between the mathematic equations and Purescript it self might have been cool.

## Monoids:

The section about the laws:
```
Closure.  \forall x, y \in X.\; x * y \in X .
Associativity.  \forall x, y, z \in X.\; (x * y) * z = x * (y * z) .
Identity.  \exists e \in X.\; \forall x \in X.\; e * x = x * e = x .
```
I would explain a little more into these laws and how they work, again maybe with PS examples?

## Groups:
After exercise 3.1 I was lost. Wasn't able to connect as the pace seemed to have stepped up greatly compared to how Logic was explained.

Hope this helps :)

**Comment by hdgarrood** [comment]
This definitely does help, thanks!

Is it clear that the laws are supposed to match up with the groups of 3 statements in each of the 3 examples I gave earlier in the chapter? Perhaps it would help to give some examples of things that fail to be monoids?

For example, if we imagine the set {0, 1, 2, 3, 4, 5} together with + as the operator, it satisfies associativity and identity, but not closure, because the sum of two elements of that set isn't always in the set: e.g. 5 + 1 = 6, which isn't in the set.

For an example of something failing to be a monoid because of associativity, we might take floating point numbers under addition (which I only found out recently)! Try `(0.1 + 0.2) + 0.3` vs `0.1 + (0.2 + 0.3)` in a console.

An example of something that fails to be a monoid because of a lack of an identity element could be the set of even integers under multiplication, since 1 is not in the set of even numbers.

---

You're not the first to mention PS examples and I'm definitely considering adding some, but I'm also a bit reluctant to do too many, because although these concepts do translate into PS very well compared to other programming languages, there is still some impedance mismatch.

For example, a set in mathematics tends to be represented as a type in PureScript. However, a particular object can exist in many different sets in a way that isn't really compatible with how type-checking works; there's no neat way of asking for an even number type in PureScript such that `2` can have this type but e.g. `3` can't. Similarly there's nothing in mathematics (at least, not as far as I know) that corresponds to newtypes like `Additive` or `Multiplicative`, because you basically don't need them, you can usually guess which monoid is being talked about from context.

**Comment by Cmdv** [comment]
Very interesting I never knew about the floating points not having associativity!! it's the same in Haskell too just tried it in ghci!!

> Perhaps it would help to give some examples of things that fail to be monoids?
A demonstration of what fails is always good way to superb way to clarify things, that's a great idea :)

I'd miss understood closure, I was thinking in terms of JS closure within a function hehe

I agree with you though that maybe having too many PS examples will detract but you might be able to sneak a couple give the tittle. But over all it was very interesting and came at a right time as I've been learning more about Monoids and Semigroups 😄 👍

**Comment by hdgarrood** [comment]
I'd quite like to work out why you got stuck on 3.1, is it that you don't understand what's being asked or something else?

**Comment by hdgarrood** [comment]
I've expanded the Groups section and also added solutions to the exercises in an appendix. Would you be able to have another look and let me know if it's clearer now?

**Comment by Cmdv** [comment]
@hdgarrood sorry I totally forgot to reply to your first question, I'll take a look at the new version and see why I was stuck after 3.1 :)

**Comment by hdgarrood** [comment]
No worries, thanks again :)

**Comment by hdgarrood** [comment]
Oops, sorry, I meant I expanded the *monoids* section, not groups.
